// client/src/App.vue
<template>
  <router-view />
</template>

<script lang="ts">
// import { createTRPCProxyClient, httpBatchLink } from '@trpc/client';
// import type { AppRouter } from '../path/to/server/trpc';
import { defineComponent } from 'vue';
// import { VueQueryPlugin } from "@tanstack/vue-query";

export default defineComponent({
  name: 'App',
});
</script>

// browser/src/App.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider } from "@tanstack/react-router";
import { router } from "./routes/routes";
import "./App.css";

function App() {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  );
}

export default App;
